### ISSUE TITLE
Смена языка - нет возможности отменить после выбора

### ISSUE THREAD

**Issue by shirokolobov** [trikset/trikRuntime#331]
В появляющемся меню есть только «OK»

**Comment by ilyashir** [comment]
Еще на французкий сейчас не меняет.

**Comment by anastasiia-kornilova** [comment]
@iakov, что с французским -- насколько он сейчас актуален?

**Comment by anastasiia-kornilova** [comment]
@ilyashir, добавила обозначенную тобой проблему в #354, она пока не так актуально как первая без обновленных французских переводов.
