### ISSUE TITLE
Studio crashes when while True:

### ISSUE THREAD

**Issue by khodand** [trikset/trikRuntime#478]
Studio crashes with no output when you try to execute such code:
```python
import sys
import time
import random
import math

class Program():
  __interpretation_started_timestamp__ = time.time() * 1000
  def execMain(self):
    i = 0;
    print("start")
    while True:
      print(i)
      i += 1
    return

def main():
  program = Program()
  program.execMain()

if __name__ == '__main__':
  main()
```

**Comment by anastasiia-kornilova** [comment]
Is it bug for runtime? Or it should be moved to TS issues?

**Comment by iakov** [comment]
To check: if this code can be interrupted from TS when is being run on controller. @khodand

**Comment by iakov** [comment]
For me works in 2D (current master): `while True: pass`

**Comment by khodand** [comment]
> 
> 
> For me works in 2D (current master): `while True: pass`

It seems like this is failing while printing in a loop

**Comment by khodand** [comment]
> 
> 
> To check: if this code can be interrupted from TS when is being run on controller. @khodand

No, it isn't

**Comment by iakov** [comment]
Reproducible in JS, but seems to be a TS issue
