### ISSUE TITLE
Add an argument of type array to the subprogram.

### ISSUE THREAD

**Issue by ilyashir** [trikset/trikRuntime#536]
Иногда требуется передать не число аргументом, а целый массив.
Просьба добавить такую возможность.

**Comment by anastasiia-kornilova** [comment]
@ilyashir, это тоже про студию. Такие проблемы лучше закидывать в https://github.com/trikset/trik-studio

**Comment by anastasiia-kornilova** [comment]
Перенесла -- https://github.com/trikset/trik-studio/issues/811
